### ISSUE TITLE
Multiple Treatments

### ISSUE THREAD

**Issue by clblanke** [sccallahan/WARPqpcr#1]
Hello,

I am trying to use this program on qPCR data where I have biological replicates and multiple treatments. I have managed to reach the code for relative expression on biological replicate data but I do not know how to enter multiple cases since the program seems only to accept a single case. I'm new to R so there may be something obvious I'm missing but how can I list/indicate multiple treatments for 'case'?

**Comment by sccallahan** [comment]
That's something I hope to add in a future update!

As it stands, the code on the backend is essentially a wrapper around the NormqPCR code for 2 conditions. NormqPCR requires the construction of a contrast matrix for its calculations, and I'm working on a way to make it more flexible.

If I set it up to accept 1 "control" and an arbitrary number of "cases" that are then each compared to that same control, would that solve the issue?

As a workaround for the time being, you'd have to do individual runs of the code for each case. You could basically just copy/paste the code and change variables as needed for each case. For plotting, you could then merge the output files of each run into a dataframe, then use that for ggplot input.

**Comment by clblanke** [comment]
Thank you for responding! I was really worried that I was missing something. 

I think if the program accepted 1 "control" and an arbitrary number of "cases" that would solve the issue. This is a great program. Thank you for making it!

**Comment by sccallahan** [comment]
Hi!

Just want to drop in and say I haven't forgotten about this! Things have been crazy around here with covid19, so I haven't had a chance to work on this just yet.

We'll all be working from home for the foreseeable future, so hopefully I get a bit of time to work on it!

**Comment by sccallahan** [comment]
After an awkwardly long silent time, I'm not sure I'm realistically ever going to be able to get to this. I'll gladly take a PR or something if anyone is invested. Otherwise... I can't comfortably make any guarantees.
