### ISSUE TITLE
Collaborating to prepare work for JOSS!

### ISSUE THREAD

**Issue by ssiddhantsharma** [sccallahan/WARPqpcr#2]
Hi, 
Coming from a vibrant reddit community, I wanted to suggest and ask to collaborate/contribute to submit this work at JOSS (Journal of Open Source Software). It would be a nice proponent and documenting the process in a compact paper will help the service be more accessible to interested people. **_I am definitely open for working on this._**

**Link** : https://joss.theoj.org/

**Comment by sccallahan** [comment]
Hi, sorry, I don't really have plans/time to publish this. It was/is more of a side project!
